migasar/gnomes-out

- Gemfile.lock
- app/models/gnome.rb
Modification du model booking pour mettre les arrays category, mood et color dans des constantes.
> Add constants

- app/models/gnome.rb
- db/migrate/20210817092531_add_column_to_gnomes.rb
- db/schema.rb
j'ai ajouté la colonne phot au modele Gnome et je l'ai aussi mis dans les validates
> add photo to gnomes

- app/controllers/application_controller.rb
- app/controllers/gnomes_controller.rb
- test/controllers/gnomes_controller_test.rb
j'ai ajouté le controller gnomes
> create a gnomes controller

- app/controllers/application_controller.rb
- app/controllers/gnomes_controller.rb
- app/policies/gnome_policy.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- test/policies/gnome_policy_test.rb
j'ai ajouté des actions au controller et j'ai mis a jour les policies des controlleurs (mais j'ai pas fini)
> add actions controller and policies controller

- app/controllers/bookings_controller.rb
- app/policies/booking_policy.rb
- test/controllers/bookings_controller_test.rb
- test/policies/booking_policy_test.rb
Ajout du contrôleur  booking avec les différentes méthodes
> Add bookings controller

- app/controllers/gnomes_controller.rb
- app/controllers/pages_controller.rb
- app/views/shared/_navbar.html.erb
Ajout des before action +  route pour la navbar
> Add skip before action and route pour accueil

- app/controllers/gnomes_controller.rb
- app/views/shared/_navbar.html.erb
j'ai rajouté l'edit ainsi que le systeme de deconnexion
> finish gnomes controller

- db/seeds.rb
Ajout des 4 users (Vous trouverez les logs dans la seed) et de 10 gnomes !
> Create seed with 4 users and 10 gnomes

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/controllers/gnomes_controller.rb
- app/views/gnomes/index.html.erb
- app/views/gnomes/show.html.erb
- app/views/shared/_search-category.html.erb
j'ai fait vite fait les views du show et index des gnomes pour voir si la barre de recherche marche
> view index et show

- db/migrate/20210818093656_add_validated_to_bookings.rb
- db/schema.rb
I created the column  `validated` in the table `bookings` with `false` as default value.
I didn't modify the validation rules of the model `Booking`. but I think that it should work as intended like this.
> Added field Validated to table Booking in DB schema

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/models/gnome.rb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_footer.html.erb
- db/seeds.rb
> footer done

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- app/controllers/gnomes_controller.rb
- app/views/gnomes/index.html.erb
> footer done titres category done

- app/controllers/bookings_controller.rb
- app/views/bookings/show.html.erb
- I put most of the basic code in `show.html.erb` for bookings
- but I didn't tested the dynamic code in my page (waiting for the implementation of the method booking#create)
- I didn't created yet the associated stylesheets
> Created the HTML for the view of the Booking#show

- app/assets/stylesheets/components/_index.scss
> Correction ; index file

- Gemfile
- Gemfile.lock
- db/seeds.rb
> add faker users et gnomes

- app/controllers/gnomes_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/views/layouts/application.html.erb
- app/views/shared/_mapbox.html.erb
- package.json
- yarn.lock
mapbox faite, il faut ajouter le ficher _mapbox.html.erb dans l'index
> mapbox create

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/gnomes/index.html.erb
grid de l'index gnome terminée
> grid index gnome done

- app/assets/stylesheets/components/_colors.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
navbar modifiées avec les messages
> navbar done

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_formsearch.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/gnomes_controller.rb
- app/views/gnomes/index.html.erb
- app/views/shared/_search-category.html.erb
barre de recherche terminée sur la home page
> search barre done

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_images.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/bookings/show.html.erb
- app/views/gnomes/show.html.erb
> show booking done

- app/assets/stylesheets/components/_dashboard.scss
- app/views/pages/dashboard.html.erb
Correction de l'affichage du DashBoard
> Front dashbord

- app/assets/stylesheets/components/_buttons.scss
- app/controllers/bookings_controller.rb
- app/views/bookings/show.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_flashes.html.erb
- config/routes.rb
- sketched basic layout of dual buttons (_valider ma commande_ / _nouvelle recherche_)
- created the workflow to change `booking.validated` to `true`
- created missing shared layout to activate alerts
- the alert is not displayed yet, but the rest seems to work fine -> I will debug the display later on
> Created booking validation action from button
